### ISSUE TITLE
sbt tooling

### ISSUE THREAD

**Issue by chandu0101** [scalajs-react-interface/incubator#4]
https://github.com/scalajs-react-interface/sbt-sri-platform

Mobile : 

Currently our plugin supports ,sbt tasks for scala.js code compilation , lets extend them to install npm packages ,run apps, bundling process,..

Web : 

Find a way to add `scalajs-bundler ` as opt in

**Comment by chandu0101** [comment]
need more research!.
recently callstack released webpack based packager for react-native : https://github.com/callstack-io/haul

**Comment by frgomes** [comment]
@chandu0101 : I suggest closing this issue and opening separate issues for every topic in particular or maybe creating several checkboxes so that we can track topics already covered.

**Comment by chandu0101** [comment]
@frgomes  i am not concerned about sri-mobile anymore. please take full command over mobile infra :)
